=== guetlein/daceDS/Frontend/backend/data/definitions/layer_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Layer",
    "description": "Layer description",
    "type": "object",
    "definitions": {
        "compound": {
            "type": "object",
            "required": [
                "name",
                "key",
                "isGettable",
                "isObservable",
                "isPersistent",
                "isSettable"
            ],
            "properties": {
                "name": {
                    "description": "The compound's name",
                    "type": "string"
                },
                "key": {
                    "description": "The compound's key",
                    "$ref": "#/definitions/primitive"
                },
                "compounds": {
                    "description": "Embedded compound structures",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/compound"
                    }
                },
                "methods": {
                    "description": "Interface extensions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/method"
                    }
                },
                "primitives": {
                    "description": "Embedded primitive attributes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/primitive"
                    }
                },
                "isGettable": {
                    "description": "Is there a getter?",
                    "type": "boolean",
                    "default": false
                },
                "isObservable": {
                    "description": "Is there an observer?",
                    "type": "boolean",
                    "default": false
                },
                "isPersistent": {
                    "description": "Are contents persistent?",
                    "type": "boolean",
                    "default": false
                },
                "isReferenceRelated": {
                    "description": "Is this related to the domain reference?",
                    "type": "boolean",
                    "default": false
                },
                "isSettable": {
                    "description": "Is there a setter?",
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "method": {
            "type": "object",
            "required": [
                "name",
                "input",
                "output"
            ],
            "properties": {
                "name": {
                    "description": "The attribute's name",
                    "type": "string"
                },
                "input": {
                    "description": "A list of attributes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output": {
                    "description": "Return type of method",
                    "type": "string"
                },
                "description": {
                    "description": "A further description",
                    "type": "string"
                }
            }
        },
        "primitive": {
            "type": "object",
            "required": [
                "name",
                "type",
                "isGettable",
                "isSettable",
                "isObservable"
            ],
            "properties": {
                "name": {
                    "description": "The attribute's name",
                    "type": "string"
                },
                "type": {
                    "description": "The attribute's type, e.g. 'double'. This has nothing to do with json types",
                    "type": "string"
                },
                "isGettable": {
                    "description": "Will there be a getter?",
                    "type": "boolean",
                    "default": false
                },
                "isObservable": {
                    "description": "Will there be an observer?",
                    "type": "boolean",
                    "default": false
                },
                "isReferenceRelated": {
                    "description": "Is this related to the domain reference?",
                    "type": "boolean",
                    "default": false
                },
                "isSettable": {
                    "description": "Will there be a setter?",
                    "type": "boolean",
                    "default": false
                },
                "unit": {
                    "description": "The attribute's unit e.g. ms",
                    "type": "string"
                },
                "description": {
                    "description": "A further description",
                    "type": "string"
                }
            }
        }
    },
    "properties": {
        "name": {
            "description": "The layer's name",
            "type": "string"
        },
        "domain": {
            "description": "The layer's domain",
            "type": "string"
        },
        "version": {
            "description": "Version of the layer definition",
            "type": "number"
        },
        "ndm": {
            "description": "The layer's native data model",
            "$ref": "#/definitions/compound"
        },
        "compounds": {
            "description": "The layer's compound structures",
            "type": "array",
            "items": {
                "$ref": "#/definitions/compound"
            }
        },
        "methods": {
            "description": "Interface extensions",
            "type": "array",
            "items": {
                "$ref": "#/definitions/method"
            }
        },
        "primitives": {
            "description": "The layer's primitive attributes",
            "type": "array",
            "items": {
                "$ref": "#/definitions/primitive"
            }
        }
    },
    "required": [
        "name",
        "domain",
        "ndm",
        "version"
    ]
}

=== guetlein/daceDS/Frontend/backend/data/layers/802.11p_PHY.json
{
    "name": "802.11p_PHY",
    "domain": "communication",
    "version": 1,
    "ndm": {
        "name": "message",
        "isPersistent": false,
        "isGettable": true,
        "isSettable": false,
        "isObservable": true,
        "compounds": [],
        "key": {
            "name": "messageID",
            "type": "string",
            "isGettable": false,
            "isSettable": false,
            "isObservable": false
        },
        "methods": [],
        "primitives": [
            {
                "name": "transmissionPower",
                "type": "double",
                "isGettable": true,
                "isSettable": false,
                "isObservable": false,
                "unit": "mW"
            },
            {
                "name": "origin",
                "type": "vec3",
                "isGettable": true,
                "isSettable": false,
                "isObservable": false,
                "unit": "m"
            },
            {
                "name": "header",
                "type": "string",
                "isGettable": true,
                "isSettable": true,
                "isObservable": false,
                "unit": "veh/m"
            },
            {
                "name": "payload",
                "type": "string",
                "isGettable": true,
                "isSettable": true,
                "isObservable": false
            }
        ]
    },
    "compounds": [
    ],
    "methods": [
    ],
    "primitives": [
    ]
}

=== guetlein/daceDS/Frontend/backend/data/layers/micro.json
{
    "name": "micro",
    "domain": "traffic",
    "version": 1,
    "ndm": {
        "name": "vehicle",
        "isPersistent": false,
        "isGettable": true,
        "isSettable": false,
        "isObservable": true,
        "compounds": [],
        "key": {
            "name": "vehicleID",
            "type": "string",
            "isGettable": false,
            "isSettable": false,
            "isObservable": false
        },
        "methods": [],
        "primitives": [
            {
                "name": "acceleration",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "m/s2",
                "description" : "will lead to: interaction[...]micro.vehicle.acceleration.get, interaction[...]micro.vehicle.acceleration.ret, provision[...]micro.vehicle.acceleration"
            },
            {
                "name": "angle",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "deg"
            },
            {
                "name": "edge",
                "type": "string",
                "isGettable": true,
                "isReferenceRelated": true,
                "isSettable": true,
                "isObservable": true
            },
            {
                "name": "lane",
                "type": "int",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true
            },
            {
                "name": "position",
                "type": "Vec3",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "m,m,m"
            },
            {
                "name": "positionEdge",
                "type": "double",
                "isGettable": true,
                "isSettable": false,
                "isObservable": true,
                "unit": "m",
                "description": "distance to beginning of current edge"
            },
            {
                "name": "route",
                "type": "list_string",
                "isGettable": true,
                "isSettable": true,
                "isObservable": false
            },
            {
                "name": "slope",
                "type": "double",
                "isGettable": true,
                "isSettable": false,
                "isObservable": true,
                "unit": "deg"
            },
            {
                "name": "speed",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "m/s"
            },
            {
                "name": "type",
                "type": "string",
                "isGettable": true,
                "isSettable": false,
                "isObservable": false
            }
        ]
    },
    "compounds": [
        {
            "name": "edge",
            "isReferenceRelated": true,
            "isPersistent": false,
            "isGettable": true,
            "isSettable": false,
            "isObservable": true,
            "compounds": [     ],
            "key": {
                "name": "edgeID",
                "type": "string",
                "isGettable": false,
                "isSettable": false,
                "isObservable": false
            },
            "methods": [
                {
                    "name": "setAllowedTypes",
                    "input": ["integer", "list_string"],
                    "output": "void"
                },
                {
                    "name": "getAllowedTypes",
                    "input": ["integer"],
                    "output": "list_string"
                },
                {
                    "name": "getLaneNumber",
                    "input": [],
                    "output": "integer"
                },
                {
                    "name": "getLaneGradient",
                    "input": ["integer"],
                    "output": "double"
                },
                {
                    "name": "getLaneLength",
                    "input": ["integer"],
                    "output": "double"
                },
                {
                    "name": "getLaneWidth",
                    "input": ["integer"],
                    "output": "double"
                }
            ],
            "primitives": [
                {
                    "name": "emission",
                    "type": "string",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true,
                    "description" : "just a string with some calculated emission numbers"
                },
                {
                    "name": "flow",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "occupancy",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "speed",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true,
                    "unit": "m/s"
                },
                {
                    "name": "vehicles",
                    "type": "list_vehicle",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "vehicleIDs",
                    "type": "list_string",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                }
            ]
        },{
            "name": "detector",
            "isPersistent": true,
            "isGettable": true,
            "isSettable": false,
            "isObservable": true,
            "compounds": [],
            "key": {
                "name": "detectorID",
                "type": "string",
                "isGettable": false,
                "isSettable": false,
                "isObservable": false
            },
            "methods": [],
            "primitives": [
                {
                    "name": "values",
                    "type": "map_[boolean,double,integer,string]",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true,
                    "description" : "detector's values, very generic because no further knowledge, key is det.attribute name, value is det.value"
                }]
        }
    ],
    "methods": [
        {
            "name": "exportSim",
            "input": [],
            "output": "void"
        }
    ],
    "primitives": [
        {
            "name": "simTime",
            "type": "long",
            "isGettable": true,
            "isSettable": false,
            "isObservable": true,
            "unit": "ms"
        },
        {
            "name": "boundaries",
            "type": "Vec4",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false,
            "unit": "m,m,m,m"
        },
        {
            "name": "offset",
            "type": "Vec2",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false,
            "unit": "m,m"
        },
        {
            "name": "roadMap",
            "type": "string",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false
        }
    ]
}

=== guetlein/daceDS/Frontend/backend/data/layers/macro.json
{
    "name": "macro",
    "domain": "traffic",
    "version": 1,
    "ndm": {
        "name": "edge",
        "isPersistent": false,
        "isGettable": true,
        "isSettable": false,
        "isObservable": true,
        "compounds": [],
        "key": {
            "name": "edgeID",
            "type": "string",
            "isGettable": false,
            "isSettable": false,
            "isObservable": false
        },
        "methods": [],
        "primitives": [
            {
                "name": "speed",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "m/s"
            },
            {
                "name": "flow",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "veh/h"
            },
            {
                "name": "occupation",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "veh/m"
            },
            {
                "name": "type",
                "type": "string",
                "isGettable": true,
                "isSettable": false,
                "isObservable": false
            }
        ]
    },
    "compounds": [
    ],
    "methods": [
    ],
    "primitives": [
    ]
}

=== guetlein/daceDS/Frontend/backend/data/layers/meso.json
{
    "name": "meso",
    "domain": "traffic",
    "version": 1,
    "ndm": {
        "name": "vehicle",
        "isPersistent": false,
        "isGettable": true,
        "isSettable": false,
        "isObservable": true,
        "compounds": [],
        "key": {
            "name": "vehicleID",
            "type": "string",
            "isGettable": false,
            "isSettable": false,
            "isObservable": false
        },
        "methods": [],
        "primitives": [
            {
                "name": "edge",
                "type": "string",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true
            },
            {
                "name": "lane",
                "type": "int",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true
            },
            {
                "name": "route",
                "type": "list_string",
                "isGettable": true,
                "isSettable": true,
                "isObservable": false
            },
            {
                "name": "speed",
                "type": "double",
                "isGettable": true,
                "isSettable": true,
                "isObservable": true,
                "unit": "m/s"
            },
            {
                "name": "type",
                "type": "string",
                "isGettable": true,
                "isSettable": false,
                "isObservable": false
            }
        ]
    },
    "compounds": [
        {
            "name": "edge",
            "isPersistent": false,
            "isGettable": true,
            "isSettable": false,
            "isObservable": true,
            "compounds": [     ],
            "key": {
                "name": "edgeID",
                "type": "string",
                "isGettable": false,
                "isSettable": false,
                "isObservable": false
            },
            "methods": [],
            "primitives": [
                {
                    "name": "flow",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "occupancy",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "speed",
                    "type": "double",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true,
                    "unit": "m/s"
                },
                {
                    "name": "vehicles",
                    "type": "list_vehicle",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                },
                {
                    "name": "vehicleIDs",
                    "type": "list_string",
                    "isGettable": true,
                    "isSettable": false,
                    "isObservable": true
                }
            ]
        }
    ],
    "methods": [
        {
            "name": "exportSim",
            "input": [],
            "output": "void"
        }
    ],
    "primitives": [
        {
            "name": "simTime",
            "type": "long",
            "isGettable": true,
            "isSettable": false,
            "isObservable": true,
            "unit": "ms"
        },
        {
            "name": "boundaries",
            "type": "Vec4",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false,
            "unit": "m,m,m,m"
        },
        {
            "name": "offset",
            "type": "Vec2",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false,
            "unit": "m,m"
        },
        {
            "name": "roadMap",
            "type": "string",
            "isGettable": true,
            "isSettable": false,
            "isObservable": false
        }
    ]
}
